/** @type {import('tailwindcss').Config} */
const defaultTheme = require("tailwindcss/defaultTheme");
module.exports = {
  important: true,
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: { xxs: "270px", xs: "350px", ...defaultTheme.screens },
      colors: {
        swGray: "#737373",
        swGrey10: "#FAFAFA",
        swGrey25: "#F4F4F4",
        swGrey50: "#EAEAEA",
        swGrey100: "#BEBEBE",
        swGrey200: "#9F9F9F",
        swGrey400: "#585858",
        swGrey500: "#2E2E2E",
        swLightGray: "#f5f5f5",
        swBlue: "#2769B3",
        swBlue500: "#9CBADC",
        swBlueActiveStateBg: "#E9F0F7",
        swDarkBlue: "#2360A3",
        swDarkBlueOutline: "#1C4B7F",
        swLightBlue: "#1073F4",
        swBrown: "#545454",
        swDarkBlue: "#153A62",
        swGreen: "#17B26A",
        swGreen200: "#94DCBA",
        swGreen700: "#107E4B",
        swDarkGreen: "#0D623A",
        swIndicatorYellow: "#F9C00F",
        swYellow600: "#E3AF0E",
        swIndicatorPink: "#FF00AE",
        swTextColor: "#545454",
        swBlack: "#333333",
        swPurple: "#BB00FF",
        swIndicatorLightRed: "#F04438",
        swDarkRed: "#84251F",
        swIndicatorPurple: "#D154FF",
        swIndicatorDarkRed: "#AA3028",
        swLightBlueIndcatorBg: "#F0F6FE",
        swLightPinkIndcatorBg: "#FFF0FA",
        swLightGreenIndcatorBg: "#F1FDF8",
        swLightPurpleIndcatorBg: "#FBF0FF",
        swGold: "#B1880B",
      },
    },
  },
  env: {
    API_URL: process.env.NEXT_PUBLIC_API_URL,
  },
  plugins: [],
};
